# Generated by Django 3.0.4 on 2020-04-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published'), ('2', 'Published')], max_length=1)),
            ],
        ),
    ]
